#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
spring:
  h2:
    console:
    enabled: true
    path: /h2-console

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: js082917
    url: jdbc:mysql://localhost:3306/csemall?useSSL=false&allowPublicKeyRetrieval=true?serverTimezone=Asia/Seoul
    username: root

  #  jpa:
  #    database: mysql
  #    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
  #    hibernate:
  #      ddl-auto: update
  #    show-sql : true
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQL5Dialect
  #    how_sql: true
  #    format_sql: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

handlebars:
  suffix: .html
  expose-session-attributes: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 9076

thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"
